management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 10111
    servlet:
      context-path: /
    ssl:
      enabled: false
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_test?serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



my:
  name: SA
  age: 22

person:
  name: AnaduseSA
  age: 22
  max: ${random.int(10)}
  uuid: ${random.uuid}
  value: ${random.value}
  greeting: hi.I'm ${person.name}



